test = {   'name': 'q6c',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> callable(missing_value_fast) and isinstance(missing_value_fast([2, 1, 5, 3]), int)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> ex1 = missing_value_fast([2, 1, 5, 3])\n>>> ex2 = missing_value_fast([10, 9, 1, 6, 5, 7, 2, 4, 3])\n>>> ex1 == 4 and ex2 == 8\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
